"""Deduplication and merge engine for assets and relations.

This component is deliberately deterministic: identity is based on canonical
keys generated by each asset model. When duplicates are detected, evidence and
metadata are aggregated rather than overwritten.
"""

from __future__ import annotations

import threading
from dataclasses import dataclass
from typing import Iterable

from reconx.core.assets import BaseAsset
from reconx.core.relations import Relation


@dataclass(slots=True)
class MergeResult:
    """Result of inserting an asset/relation into the dedup index."""

    item_id: str
    is_new: bool
    changed: bool


class DedupEngine:
    """Thread-safe in-memory deduplication index.

    The storage backend remains the source of record, but this in-memory layer
    provides low-latency merge decisions during event processing.
    """

    def __init__(self) -> None:
        self._assets_by_identity: dict[tuple[str, str], BaseAsset] = {}
        self._assets_by_id: dict[str, BaseAsset] = {}
        self._relations_by_id: dict[str, Relation] = {}
        self._lock = threading.RLock()

    def ingest_asset(self, asset: BaseAsset) -> tuple[BaseAsset, MergeResult]:
        """Insert or merge a typed asset."""

        identity = (asset.asset_type, asset.canonical_key)
        with self._lock:
            current = self._assets_by_identity.get(identity)
            if current is None:
                self._assets_by_identity[identity] = asset
                self._assets_by_id[asset.id] = asset
                return asset, MergeResult(item_id=asset.id, is_new=True, changed=True)

            changed = current.merge_from(asset)
            self._assets_by_id[current.id] = current
            return current, MergeResult(item_id=current.id, is_new=False, changed=changed)

    def ingest_relation(self, relation: Relation) -> tuple[Relation, MergeResult]:
        """Insert or merge a relation edge."""

        with self._lock:
            current = self._relations_by_id.get(relation.id)
            if current is None:
                self._relations_by_id[relation.id] = relation
                return relation, MergeResult(item_id=relation.id, is_new=True, changed=True)

            changed = current.merge_from(relation)
            return current, MergeResult(item_id=current.id, is_new=False, changed=changed)

    def get_asset(self, asset_id: str) -> BaseAsset | None:
        """Fetch an asset by ID."""

        with self._lock:
            return self._assets_by_id.get(asset_id)

    def get_relation(self, relation_id: str) -> Relation | None:
        """Fetch a relation edge by ID."""

        with self._lock:
            return self._relations_by_id.get(relation_id)

    def all_assets(self) -> list[BaseAsset]:
        """Return all currently indexed assets."""

        with self._lock:
            return list(self._assets_by_id.values())

    def all_relations(self) -> list[Relation]:
        """Return all currently indexed relations."""

        with self._lock:
            return list(self._relations_by_id.values())

    def load_assets(self, assets: Iterable[BaseAsset]) -> None:
        """Bulk-load assets into the index, merging duplicates."""

        for asset in assets:
            self.ingest_asset(asset)

    def load_relations(self, relations: Iterable[Relation]) -> None:
        """Bulk-load relation edges into the index, merging duplicates."""

        for relation in relations:
            self.ingest_relation(relation)

    def summary(self) -> dict[str, int]:
        """Return lightweight index counters for diagnostics."""

        with self._lock:
            return {
                "assets": len(self._assets_by_id),
                "relations": len(self._relations_by_id),
                "identities": len(self._assets_by_identity),
            }
